### ISSUE TITLE
Organ Grinder feature request

### ISSUE THREAD

**Issue by Beam02** [JackKBroome/Carat_BOTC#10]
When Organ Grinder is in play, it would be nice if users were discouraged as much as possible from voting publicly as it goes against the spirit of the role. My suggestion is to check if the Organ grinder is in the json for the town sqyare, and if it is, when a user attempts to vote publicly using >Vote, that the command would be deleted promptly from the public chat history, and the user DM'd to remind them to vote privately instead using the >PrivateVote function in their ST thread.

public_vote command(){
      if(organ_grinder) {
          delete public command
          DM user
}
   else{
      existing functionality
}

**Comment by Qaysed** [comment]
Implemented in [PR 11](https://github.com/JackKBroome/Carat_BOTC/pull/11)
