### ISSUE TITLE
Bot throws exception when it doesn't have a profile pic. 

### ISSUE THREAD

**Issue by jacksonzck** [JackKBroome/Carat_BOTC#13]
When the bot doesn't have a profile picture, url=self.bot.user.avatar.url is None. 
This causes anyone_embed.set_thumbnail(url=self.bot.user.avatar.url) to throw an exception, as it's being passed in None as an argument.

**Comment by JackKBroome** [comment]
Thank you for the feedback.
Given that it's only intended to work as a single instance on the BOTC Unofficial (as far as I'm aware) right now, we're not looking to replace all the instances another solution.
